#!/usr/bin/env python3
"""Sync packaging/aos_validator_mcp/_validate_pure.py from core/validate_pure.py."""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

_TOOL_ROOT = Path(__file__).resolve().parents[2]
_CANONICAL = _TOOL_ROOT / "core" / "validate_pure.py"
_CANONICAL_BR = _TOOL_ROOT / "core" / "blast_radius.py"
_DIST_BR = _TOOL_ROOT / "packaging" / "aos_validator_mcp" / "blast_radius.py"
_CANONICAL_PATTERNS = _TOOL_ROOT / "core" / "blast_radius_patterns.json"
_DIST_PATTERNS = _TOOL_ROOT / "packaging" / "aos_validator_mcp" / "blast_radius_patterns.json"
_DIST_COPY = _TOOL_ROOT / "packaging" / "aos_validator_mcp" / "_validate_pure.py"
_DIST_HEADER = '''"""
AOS Compliance Validator — pure validation functions (distribution bundle).

Synced from upstream canonical source. Do not edit this file directly.
"""

'''


def _code_body_hash(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    if text.startswith('"""'):
        end = text.find('"""', 3)
        if end != -1:
            text = text[end + 3 :].lstrip("\n")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    if not _CANONICAL.is_file():
        print(f"FATAL: missing {_CANONICAL}", file=sys.stderr)
        return 2

    if not args.check_only:
        body = _CANONICAL.read_text(encoding="utf-8")
        if body.startswith('"""'):
            end = body.find('"""', 3)
            if end != -1:
                body = body[end + 3 :].lstrip("\n")
        _DIST_COPY.write_text(_DIST_HEADER + body, encoding="utf-8")
        print(f"OK: synced -> {_DIST_COPY}")
        if _CANONICAL_BR.is_file():
            shutil.copy2(_CANONICAL_BR, _DIST_BR)
            print(f"OK: synced -> {_DIST_BR}")
        if _CANONICAL_PATTERNS.is_file():
            shutil.copy2(_CANONICAL_PATTERNS, _DIST_PATTERNS)
            print(f"OK: synced -> {_DIST_PATTERNS}")

    if not _DIST_COPY.is_file():
        return 2
    if _code_body_hash(_CANONICAL) != _code_body_hash(_DIST_COPY):
        print("FAIL: code-body hash mismatch", file=sys.stderr)
        return 1
    print("OK: code-body hash match")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
